use_frameworks!

platform :ios, '12.0'

target 'DMengAdSDK_Example' do
  pod 'DMengAdSDK', :path => '../'
#  pod 'DMengAdSDK/DMengAdSDK', :path => '../'
  pod 'DMengAdSDK/DMAdSDKAdapter', :path => '../'
#  pod 'DMengAdSDK/GMAdSDKAdapter', :path => '../'
  pod 'DMengAdSDK/DMengSDKAdapter', :path => '../'

  target 'DMengAdSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
