use_frameworks!

platform :ios, '9.0'

end
target 'DMengAdSDK_Example' do
  pod 'DMengAdSDK', :path => '../'

  target 'DMengAdSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
